name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  environment: sgdotcom
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
        redis-version: [7]

    steps:
      - uses: actions/checkout@v3

      - name: Start Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Start Redis
        uses: supercharge/redis-github-action@1.6.0
        with:
          redis-version: ${{ matrix.redis-version }}

      - run: npm ci

      - name: Run tests
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: npm test
