name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        redis-version: [6, 7]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Start Redis
        uses: supercharge/redis-github-action@1.6.0
        with:
          redis-version: ${{ matrix.redis-version }}

      - run: npm ci
      - run: npm test
